/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.merscwog.app

import groovy.transform.CompileStatic
import org.codehaus.groovy.control.CompilerConfiguration
import org.codehaus.groovy.control.customizers.ASTTransformationCustomizer
import org.merscwog.sandbox.StaticTypedBinding

import org.merscwog.sandbox.SandboxingBindingConstraints

/**
 * For now, this is the "App" class, but will need to pull out the scripting stuff to either a library or
 * within some other helper class.
 */
class App {
    private static final String SCRIPT_TEXT = '''
        println 'bob'
        println hi
        //['bob'].indices
        //System.exit(-1)
        2
    '''

    @SuppressWarnings(['Println', 'CatchThrowable'])
    static void main(String[] args) {
        CompilerConfiguration compilerConfig = new CompilerConfiguration()
        ASTTransformationCustomizer customizer = new ASTTransformationCustomizer(
                ['extensions': 'org.merscwog.sandbox.SandboxingTypeCheckingExtension'],
                CompileStatic)
        compilerConfig.addCompilationCustomizers(customizer)

        StaticTypedBinding staticTypedBinding = new StaticTypedBinding()
        staticTypedBinding.setVariableWithType('hi', 'Hello World', String)
//        Map<String, ClassNode> variableTypes = staticTypedBinding.variablesToTypes
//        Set<Pattern> allowedMethods = [~/groovy\.lang\.Script#println(.*)/]
//        Set<Pattern> allowedProperties = [~/java\.util\.Collection#indices/]

        Challenge challenge = new Challenge().tap {
            variableTypes = staticTypedBinding.variablesToTypes
            allowedMethods = [~/groovy\.lang\.Script#println(.*)/]
            allowedProperties = [~/java\.util\.Collection#indices/]
        }

        //SandboxingBindingConstraints.ACTIVE_VALUES.set(new SandboxingBindingConstraints(variableTypes, allowedMethods, allowedProperties))
        SandboxingBindingConstraints.ACTIVE_VALUES.set(new SandboxingBindingConstraints(challenge.variableTypes,
                challenge.allowedMethods,
                challenge.allowedProperties))
        GroovyShell shell = new GroovyShell(staticTypedBinding, compilerConfig)

        Script script = shell.parse(SCRIPT_TEXT)
        Object scriptResult = script.run()
        if (scriptResult) {
            try {
                Object expectedResult = challenge.expectedResult
                assert scriptResult == expectedResult
                println 'You PASSED!'
            } catch (Throwable t) {
                println t.message
                println 'You FAILED!'
            }
        } else {
            println 'Need something to return, so FAILED!'
        }
    }
}
